version: '3'
services:
  mysql:
    restart: always
    build:
      context: .
      dockerfile: extra/mysql/Dockerfile
      #args:
      #  MODE: prod
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    volumes:
      - /var/log/mysql:/var/log/mysql

  cache:
    restart: always
    build:
      context: .
      dockerfile: extra/cache/Dockerfile
      #args:
      #  MODE: prod
    expose:
      - "11211"

  hhvm:
    restart: always
    build:
      context: .
      dockerfile: extra/hhvm/Dockerfile
      #args:
      #  MODE: prod
    depends_on:
      - mysql
      - cache
    expose:
      - "9000"
    volumes:
      - /var/log/hhvm:/var/log/hhvm

  nginx:
    restart: always
    build:
      context: .
      dockerfile: extra/nginx/Dockerfile
      #args:
      #  MODE: prod
    depends_on:
      - hhvm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/nginx:/var/log/nginx
